name = "NonconvexPercival"
uuid = "4296f080-e499-44ba-a02c-ae40015c44d5"
authors = ["Mohamed Tarek <mohamed82008@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLPModelsModifiers = "e01155f1-5c6f-4375-a9d8-616dd036575f"
NonconvexCore = "035190e5-69f1-488f-aaab-becca2889735"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Percival = "01435c0c-c90d-11e9-3788-63660f8fbccc"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
ADNLPModels = "0.1, 0.2, 0.3"
NLPModelsModifiers = "0.1, 0.2, 0.4"
NonconvexCore = "0.1.4"
Parameters = "0.12"
Percival = "0.3.1"
Reexport = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
